import {
  BookOpen,
  Bot,
  Brain,
  Bug,
  CalendarDays,
  Cpu,
  Database,
  DollarSign,
  FileText,
  FolderOpen,
  Frame,
  GitBranch,
  Image,
  ListChecks,
  ListOrdered,
  Lock,
  type LucideIcon,
  Mail,
  MessageSquare,
  Package,
  Plug,
  Search,
  Settings,
  Share2,
  SlidersHorizontal,
  Sparkles,
  Terminal,
  Timer,
  TrendingUp,
} from "lucide-react";

export type AppGroup = "Build" | "Operate" | "Data & tools" | "System";

export interface AppDefinition {
  id: string;
  path: string;
  label: string;
  shortLabel: string;
  description: string;
  group: AppGroup;
  icon: LucideIcon;
  iconClass: string;
  gradient: string;
  defaultPinned?: boolean;
}

/**
 * Canonical metadata for every first-party surface. The app rail, switcher,
 * dashboard and route labelling must consume this list rather than defining
 * their own competing app catalogs.
 */
export const APP_REGISTRY: readonly AppDefinition[] = [
  {
    id: "agents",
    path: "/agents",
    label: "Agents",
    shortLabel: "AG",
    description: "Create and manage AI agents",
    group: "Build",
    icon: Cpu,
    iconClass: "text-amber-500",
    gradient: "from-amber-500 to-orange-600",
    defaultPinned: true,
  },
  {
    id: "workflows",
    path: "/workflows",
    label: "Workflows",
    shortLabel: "WF",
    description: "Launch and monitor automated workflows",
    group: "Build",
    icon: GitBranch,
    iconClass: "text-cyan-500",
    gradient: "from-cyan-500 to-teal-600",
    defaultPinned: true,
  },
  {
    id: "tasks",
    path: "/tasks",
    label: "Tasks",
    shortLabel: "TK",
    description: "Plan, delegate, and track work across agents",
    group: "Build",
    icon: ListChecks,
    iconClass: "text-orange-500",
    gradient: "from-orange-500 to-amber-600",
  },
  {
    id: "documents",
    path: "/documents",
    label: "Documents",
    shortLabel: "DO",
    description: "Write and edit documents with AI assistance",
    group: "Build",
    icon: FileText,
    iconClass: "text-lime-500",
    gradient: "from-lime-500 to-green-600",
  },
  {
    id: "research",
    path: "/research",
    label: "Research",
    shortLabel: "RE",
    description: "Topic-based research dossiers in markdown",
    group: "Build",
    icon: Search,
    iconClass: "text-indigo-500",
    gradient: "from-indigo-500 to-violet-600",
    defaultPinned: true,
  },
  {
    id: "memories",
    path: "/memories",
    label: "Memories",
    shortLabel: "MM",
    description: "Durable categorized memories in markdown",
    group: "Build",
    icon: Brain,
    iconClass: "text-teal-500",
    gradient: "from-teal-500 to-emerald-600",
  },
  {
    id: "web-design",
    path: "/web-design",
    label: "Web Design",
    shortLabel: "WD",
    description: "Build UI mockups and design flows with agents",
    group: "Build",
    icon: Frame,
    iconClass: "text-purple-500",
    gradient: "from-purple-500 to-violet-600",
  },
  {
    id: "media",
    path: "/media",
    label: "Media",
    shortLabel: "ME",
    description: "Generate and manage images, audio, and video",
    group: "Build",
    icon: Image,
    iconClass: "text-pink-500",
    gradient: "from-pink-500 to-rose-600",
  },
  {
    id: "blog",
    path: "/blog",
    label: "Blog",
    shortLabel: "BL",
    description: "Manage posts on Ghost, WordPress, and more",
    group: "Build",
    icon: BookOpen,
    iconClass: "text-rose-500",
    gradient: "from-rose-500 to-pink-600",
  },

  {
    id: "bots",
    path: "/bots",
    label: "Bots",
    shortLabel: "BO",
    description: "Run bots in connected channels",
    group: "Operate",
    icon: Bot,
    iconClass: "text-teal-500",
    gradient: "from-teal-500 to-emerald-600",
  },
  {
    id: "scheduler",
    path: "/scheduler",
    label: "Scheduler",
    shortLabel: "SC",
    description: "Schedule recurring agent tasks and monitor runs",
    group: "Operate",
    icon: Timer,
    iconClass: "text-indigo-500",
    gradient: "from-indigo-500 to-violet-600",
  },
  {
    id: "queue",
    path: "/queue",
    label: "Queue",
    shortLabel: "QU",
    description: "Dispatch work to typed agents and track results",
    group: "Operate",
    icon: ListOrdered,
    iconClass: "text-sky-500",
    gradient: "from-sky-500 to-blue-600",
  },
  {
    id: "messaging",
    path: "/messaging",
    label: "Messaging",
    shortLabel: "MS",
    description: "Unified activity across connected channels",
    group: "Operate",
    icon: MessageSquare,
    iconClass: "text-teal-500",
    gradient: "from-teal-500 to-emerald-600",
  },
  {
    id: "social",
    path: "/social",
    label: "Social",
    shortLabel: "SO",
    description: "Connect and publish to social platforms",
    group: "Operate",
    icon: Share2,
    iconClass: "text-blue-500",
    gradient: "from-blue-500 to-indigo-600",
  },

  {
    id: "files",
    path: "/files",
    label: "Files",
    shortLabel: "FI",
    description: "Browse and manage your filesystem",
    group: "Data & tools",
    icon: FolderOpen,
    iconClass: "text-blue-500",
    gradient: "from-blue-500 to-blue-700",
    defaultPinned: true,
  },
  {
    id: "terminal",
    path: "/terminal",
    label: "Terminal",
    shortLabel: "TE",
    description: "Interactive shell sessions powered by agents",
    group: "Data & tools",
    icon: Terminal,
    iconClass: "text-stone-400",
    gradient: "from-gray-600 to-slate-800",
    defaultPinned: true,
  },
  {
    id: "email",
    path: "/email",
    label: "Email",
    shortLabel: "EM",
    description: "Read, compose, and manage emails",
    group: "Data & tools",
    icon: Mail,
    iconClass: "text-red-500",
    gradient: "from-red-500 to-rose-600",
  },
  {
    id: "calendar",
    path: "/calendar",
    label: "Calendar",
    shortLabel: "CA",
    description: "Schedule events and manage your time",
    group: "Data & tools",
    icon: CalendarDays,
    iconClass: "text-sky-500",
    gradient: "from-sky-500 to-blue-600",
  },
  {
    id: "database",
    path: "/database",
    label: "Database",
    shortLabel: "DB",
    description: "Browse datasources and tables",
    group: "Data & tools",
    icon: Database,
    iconClass: "text-cyan-500",
    gradient: "from-cyan-500 to-sky-600",
  },
  {
    id: "stocks",
    path: "/stocks",
    label: "Stocks",
    shortLabel: "ST",
    description: "Quotes, charts, history, and news",
    group: "Data & tools",
    icon: TrendingUp,
    iconClass: "text-emerald-500",
    gradient: "from-emerald-500 to-green-600",
  },

  {
    id: "skills",
    path: "/skills",
    label: "Skills",
    shortLabel: "SK",
    description: "Install, enable, and try agent skills",
    group: "System",
    icon: Sparkles,
    iconClass: "text-violet-500",
    gradient: "from-violet-500 to-fuchsia-600",
  },
  {
    id: "plugins",
    path: "/plugins",
    label: "Plugins",
    shortLabel: "PL",
    description: "Manage installed plugins and extensions",
    group: "System",
    icon: Package,
    iconClass: "text-fuchsia-500",
    gradient: "from-fuchsia-500 to-pink-600",
  },
  {
    id: "configuration",
    path: "/configuration",
    label: "Configuration",
    shortLabel: "CO",
    description: "Edit plugin and server configuration",
    group: "System",
    icon: SlidersHorizontal,
    iconClass: "text-amber-500",
    gradient: "from-amber-500 to-orange-600",
  },
  {
    id: "services",
    path: "/services",
    label: "Services",
    shortLabel: "SV",
    description: "Tools, models, hooks, and integrations",
    group: "System",
    icon: Plug,
    iconClass: "text-violet-500",
    gradient: "from-violet-500 to-purple-600",
  },
  {
    id: "metrics",
    path: "/metrics",
    label: "Metrics",
    shortLabel: "MT",
    description: "Live cost tracking across agents and models",
    group: "System",
    icon: DollarSign,
    iconClass: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "debug",
    path: "/debug",
    label: "Debugging",
    shortLabel: "DE",
    description: "Capture and inspect app and agent state",
    group: "System",
    icon: Bug,
    iconClass: "text-rose-500",
    gradient: "from-rose-500 to-red-600",
  },
  {
    id: "vault",
    path: "/vault",
    label: "Vault",
    shortLabel: "VA",
    description: "Manage encrypted credentials and secrets",
    group: "System",
    icon: Lock,
    iconClass: "text-amber-500",
    gradient: "from-yellow-500 to-amber-600",
  },
  {
    id: "settings",
    path: "/settings",
    label: "Settings",
    shortLabel: "SE",
    description: "Configure theme, apps, and preferences",
    group: "System",
    icon: Settings,
    iconClass: "text-stone-400",
    gradient: "from-stone-500 to-gray-600",
  },
] as const;

export const APP_GROUPS: readonly AppGroup[] = ["Build", "Operate", "Data & tools", "System"];
export const DEFAULT_PINNED_APP_IDS = APP_REGISTRY.filter(app => app.defaultPinned).map(app => app.id);

export function getAppById(id: string | null | undefined): AppDefinition | undefined {
  return APP_REGISTRY.find(app => app.id === id);
}

export function getActiveApp(pathname: string): AppDefinition | undefined {
  if (pathname.startsWith("/agent/")) return getAppById("agents");
  return APP_REGISTRY.find(app => pathname === app.path || pathname.startsWith(`${app.path}/`));
}
