workflows:
  brainstormingSession:
    category: "Brainstorming"
    displayName: "All-Package Brainstorming Session"
    description: "This agent will automatically run a brainstorming session for each package in the TokenRing monorepo"
    agentType: "leader"
    steps:
      - /function define js getPackageDirectories() { return (await import('fs')).globSync('pkg/*') }
      - /list @packages = getPackageDirectories()
      - |
        /for $pkg in @packages {
          /eval /agent run --neverFail --type product-design-engineer Search for all the files in $pkg/, understand the current functionality of the package, brainstorm new ideas for improving the package, and save those ideas in a 'brainstorm/prd/{idea_name}.md' file
        }