workflows:
  documentationUpdater:
    category: "Documentation"
    displayName: "All-Package Documentation Updater"
    description: "This agent will automatically update the documentation for each package in the TokenRing monorepo"
    agentType: "leader"
    steps:
      - /function define js getPackageDirectories() { return (await import('fs')).globSync('pkg/*') }
      - /list @packages = getPackageDirectories()
      - |
        /for $pkg in @packages {
          /eval /agent run --neverFail --type documentation-engineer Search for all the files in $pkg/, and methodically update the packages README to match the current code in the package;
          /eval /agent run --neverFail --type documentation-engineer Search for all the files in $pkg/, and methodically update or create documentation in docs/docs/plugins/ to match the current functionality of the package (plugin)
        }
      - /eval /agent run --neverFail --type documentation-engineer Search for all the files in app/coder/*, and methodically update the app/coder/README.md to match the current code in the package
      - /eval /agent run --neverFail --type documentation-engineer Search for all the files in app/writer/*, and methodically update the app/writer/README.md to match the current code in the package
      - /eval /agent run --neverFail --type documentation-engineer Search for pkg/*/README.md, and *.md in the project directory, and update the documentation in the project directory to match the current functionality of the packages
